adsabs/montysolr

- contrib/adsabs/src/java/org/apache/lucene/search/similarities/BM25SimilarityADS.java
- contrib/adsabs/src/test/org/adsabs/TestAdsAllFields.java
- contrib/examples/adsabs/server/solr/collection1/conf/schema.xml
added 6 fields for augmented affiliation (canonical, facets, id, etc.)
added version which asclepias will populate
added publisher which bib/import will populate
also fixed syntax error in BM25SimilarityADS
note unit tests were not passing before this change and are still failing
We will need to tweak this PR based on discussions
> schema update for aff, publisher and version

- contrib/adsabs/src/jython/jython_name_parser.py
- contrib/adsabs/src/test/org/jython/monty/TestJythonNameParser.java
processes of certain names with a ' could cause the query thread to enter an infinite loop.  it required multiple spaces after the ' character
Also discussed in a google doc at https://docs.google.com/document/d/14QJkF2LYMBT1vg4HX_rOXQ33cEM6Cwqrj9RljFuXYMs/edit#heading=h.5zlrzf6d5gjj
> fix typo in python name processing code

- contrib/examples/adsabs/server/solr/collection1/conf/solrconfig.xml
we see non-bumblebee api reqeusts for this facet
the first request after a new index causes all facet queries to block for several minutes while this facet is warmed.
> also warm facet for simbad_object_facet_hier

- contrib/examples/adsabs/server/solr/collection1/conf/solrconfig.xml
added 5 fields with _facet_hier in their name but were not already in warmup query
are there other fields that hold "sorted doc values'?
> modified facet warm query

- .gitignore
- build.xml
Fixes an issue in the `build.xml` file where Solr dependencies weren't being downloaded prior to extraction, producing build failures under certain versions of `ant`.
> Minor quality of life change + build fix

- montysolr/src/main/java/org/apache/lucene/queryparser/flexible/aqp/builders/AqpAdsabsSubQueryProvider.java
Changes the relatively inscrutable error message from `pos` when it's used with a boolean query over multiple fields (e.g. over a virtual field).
This change is a temporary resolution before we switch to broadcasting over each term in the boolean query.
> Change error for `pos` when used with a boolean query over multiple fields

- deploy/adsabs/server/solr/collection1/conf/schema.xml
Introduce a multi-valued field has that will be populated with field names (like abstract, body, author) from a curated list that will get added when the Solr record in question has a non-empty entry for that field. For example, the query `has:abstract` returns all records that have an abstract.
- The `has` field is populated in the master pipeline, not at runtime.
- Not all schema fields are represented in the list of fields the pipeline fulfills.
- Solr does no validation of the user's input.
> Add `has` field to Solr schema

- deploy/adsabs/server/solr/collection1/conf/schema.xml
A user wanted to search for titles that have the acronym LBV. With the current schema `LBV` (in caps) triggers acronym expansion, even in exact searches.
This schema change removes acronym expansion for `_nosyn` fields, which are what the exact search converts all applicable fields to at query time.
> Remove acronym filter from `_nosyn` fields

- montysolr/src/test/java/org/apache/solr/analysis/TestAdsabsTypeFulltextParsing.java
v77.2.1 removed the acronym filter from `_nosyn` filters. One of the title text searches hard-coded the previous behavior; this PR modifies that test to align with the new exact search behavior.
> Resolve test broken test case for version 77.2.1

- .gitignore
- montysolr/build.gradle.kts
- montysolr/src/test/java/org/apache/solr/handler/batch/TestBatchProviderDumpCitationCache.java
Adds retries during testing to prevent spurious build failures.
Build failures due to flaky tests prevent deployment of properly functioning code and slow down the review process.
> Add test retries

- gradle.properties
- montysolr/build.gradle.kts
We previously built Montysolr with Java 8 because there were various type errors at runtime.
This issue has been resolved.
> Change Montysolr build to use Java 11

- deploy/adsabs/server/solr/collection1/conf/schema.xml
- montysolr/src/main/java/org/apache/lucene/queryparser/flexible/aqp/processors/AqpChangeRewriteMethodProcessor.java
As SciX continues to expand into new domains we keep encountering papers outside of our well-established citation networks and read data. These metrics have worked well for astro papers, but tend to de-prioritize papers in new domains.
Adds support for the `doctype_boost` field in the schema, to be populated by the pipelines. This field is intended to be used with either the `sort` or `boost` query parameters to change document search rankings.
This PR builds on the Solr 9 release, which has not been merged (at the time this PR was originally published). The relevant commit in this branch changes `schema.xml`.
> Add `doctype_boost`

- deploy/adsabs/server/solr/collection1/conf/schema.xml
This PR adds support for SciX IDs (`scix_id`), which will be used in place of bibcodes in the future, and deprecates the `gpn` family of fields in favor of their newly-renamed `planetary_feature` counterparts.
> `scix_id` and `planetary_feature` schema additions

- deploy/adsabs/server/solr/collection1/conf/schema.xml
Add UAT ID and facet fields to the schema.
Until now the schema has only supported UAT feature names, preventing searches by ID or by group.
> Add UAT fields to the schema

- deploy/adsabs/server/solr/collection1/conf/solrconfig.xml
In `solrconfig.xml` we configure the ADS Query Parser with a list of int-valued fields. If a field isn't in this list, it will not be parsed as an int at query time, causing all int queries to fail.
This change adds `uat_id` to the list of int fields in the Solr config to resolve this issue with the field.
> Add `uat_id` to `aqp.intFields`

- deploy/adsabs/server/solr/collection1/conf/schema.xml
- montysolr/src/main/java/org/apache/solr/analysis/author/PythonicAuthorNormalizerFilter.java
Prevents author names from expanding into bare surnames ("Anna Kelbert" -> "Kelbert,").
When author names expand to bare surnames, it can produce overly greedy searches that include miscellaneous authors unrelated to the original search. This is especially bad for common author names.
> Prevent overly-greedy author name searches

- deploy/adsabs/server/solr/collection1/conf/solrconfig.xml
- montysolr/build.gradle.kts
- montysolr/src/main/java/org/apache/solr/highlight/MaxLengthHighlighter.java
As part of our agreement with publishers we set a maximum character length for highlights. This was loosely enforced using other highlighter parameters, but the unified highlighter does not support a fixed max length for all highlights-- we need an alternate enforcement mechanism.
This PR adds a highlighter with a new parameter to control the max highlight length coming from the searcher.
An alternative implementation might live in `solr-service` as we're not doing any advanced processing in Solr.
> Add config option to control max highlight length

- deploy/adsabs/server/solr/collection1/conf/solrconfig.xml
Adds the option to configure the max clause count via a system property (typically set via the command line).
We've had issues with author searches hitting the max clause limit. For our use-case it makes sense to increase this limit and _also_ set a timeout for all requests.
> Enable changing max boolean clause count via system property

- deploy/adsabs/server/solr/collection1/conf/solrconfig.xml
Adds `timeAllowed` as a default query parameter. This allows us to control the maximum amount of time a query may spend before being evicted from the searcher core.
Some longer queries have the ability to take down the entire searcher. This, hopefully, will help to resolve that issue.
> Add timeAllowed as a default query parameter

- deploy/adsabs/server/solr/collection1/conf/schema.xml
This field was added to assist the frontend in removing the [citations] document transform as a dependency; the transform was based on the citation cache, which we're working to remove from Solr entirely.
> Update the schema to include `reference_count`

- deploy/adsabs/server/solr/collection1/conf/schema.xml
- deploy/adsabs/server/solr/collection1/conf/solrconfig.xml
Adds fields to the schema to be used with boost functions.
We'd like to provide different document rankings per discipline we support. These boost factors will be dynamically swapped in to re-weight records based on the user's indicated discipline preference.
> Add Boost Fields
